# Merge vs. Rebase {#merge-vs-rebase}

:::footer
[atlassian.com/git/tutorials/merging-vs-rebasing](https://www.atlassian.com/git/tutorials/merging-vs-rebasing)
:::

## Merging Changes

In Git, there are two main ways to integrate changes from one branch into another: `merge` and `rebase`.

## Merging Changes {background-image="https://wac-cdn.atlassian.com/dam/jcr:1523084b-d05a-4f5a-bd1a-01866ec09ca3/01%20A%20forked%20commit%20history.svg?cdnVersion=1263" background-size="100% 80%" background-position="center"}

## Merging via `merge`
- the simplest way to combine branches
- a three-way merge between two branches (e.g., `main` and `feature`) and their latest common ancestor
- creates a new commit

## Merging via `merge` {background-image="https://wac-cdn.atlassian.com/dam/jcr:4639eeb8-e417-434a-a3f8-a972277fc66a/02%20Merging%20main%20into%20the%20feature%20branh.svg?cdnVersion=1263" background-size="100% 90%" background-position="center"}

## Merging via `rebase` 
- rebasing the `feature` branch onto the `main` branch means moving the start of the `feature` branch to the end of the `main` branch
- this means that commits from `feature` will be recreated on the `main` branch
- main advantage: a cleaner, more linear project history with fewer "forks"

## Merging via `rebase` {background-image="https://wac-cdn.atlassian.com/dam/jcr:3bafddf5-fd55-4320-9310-3d28f4fca3af/03%20Rebasing%20the%20feature%20branch%20into%20main.svg?cdnVersion=1263" background-size="100% 90%" background-position="center"}

## When not to use `rebase`?
- never use `git rebase` on public or collaborative branches (especially `main`)
- otherwise, part of the history may be changed or even deleted

## When not to use `rebase`? {background-image="https://wac-cdn.atlassian.com/dam/jcr:2908e0e6-f74b-4425-b5d2-f5eca8cfcd99/05%20Rebasing%20the%20main%20branch.svg?cdnVersion=1263" background-size="100% 90%" background-position="center"}

## Demo: `merge`

```bash
git clone https://github.com/bbrrck/hello.git hello-merge; cd hello-merge
git merge origin/french
# Auto-merging hello.py
git merge origin/slovak
# CONFLICT (content): Merge conflict in hello.py
# ... resolve the conflict ...
git add .
git commit
# [main cef4a72] Merge remote-tracking branch 'origin/slovak'
```

## Demo: `rebase` (french)

```bash
git clone https://github.com/bbrrck/hello.git hello-rebase; cd hello-rebase
git checkout french
git rebase main
# Successfully rebased and updated refs/heads/french.
git checkout main
git merge french
# Updating 0297280..5f6f019
# Fast-forward
#  hello.py | 11 ++++++++++-
#  1 file changed, 10 insertions(+), 1 deletion(-)
```

## Demo: `rebase` (slovak) - conflict

```bash
git checkout slovak
git rebase -i main
# ... mark the middle commit as `fixup` ...
# CONFLICT (content): Merge conflict in hello.py
# ... resolve the conflict ...
git add .
git rebase --continue
# Successfully rebased and updated refs/heads/slovak.
git checkout main
git merge slovak # Fast-forward
```


## `git log --oneline --graph --all`

::: {.columns}
::: {.column width="50%"}
Merge:

<pre class="tree">
*   <span class="hash">cef4a72</span> <span class="branch">(main)</span> Merge branch 'slovak'
|\
| * <span class="hash">163a9c3</span> <span class="branch">(slovak)</span> Add docstring for slovak
| * <span class="hash">bd67d8d</span> Fix slovak
| * <span class="hash">75fcf88</span> Add slovak
* |   <span class="hash">bc3f86b</span> Merge branch 'french'
|\ \
| * | <span class="hash">a31caf9</span> <span class="branch">(french)</span> Add docstring for french
| * | <span class="hash">6d348f3</span> Add french
| |/
* / <span class="hash">0297280</span> Add docstring for default
|/
* <span class="hash">4b4a8ad</span> Add hello.py
* <span class="hash">60d4d94</span> Initial commit
</pre>
:::
::: {.column width="50%"}
Rebase:

<pre class="tree">
* <span class="hash">ab2fda1</span> <span class="branch">(main, slovak)</span> Add docstring for slovak
* <span class="hash">806b97a</span> Add slovak
* <span class="hash">5f6f019</span> <span class="branch">(french)</span> Add docstring for french
* <span class="hash">ea40a3b</span> Add french
* <span class="hash">0297280</span> Add docstring for default
| * <span class="hash">163a9c3</span> Add docstring for slovak
| * <span class="hash">bd67d8d</span> Fix slovak
| * <span class="hash">75fcf88</span> Add slovak
|/
| * <span class="hash">a31caf9</span> Add docstring for french
| * <span class="hash">6d348f3</span> Add french
|/
* <span class="hash">4b4a8ad</span> Add hello.py
* <span class="hash">60d4d94</span> Initial commit
</pre>
:::
:::

## `git log main --oneline`

::: {.columns}
::: {.column width="50%"}
Merge (10):

<pre class="tree">
<span class="hash">cef4a72</span> <span class="branch">(main)</span> Merge branch 'slovak'
<span class="hash">bc3f86b</span> Merge branch 'french'
<span class="hash">0297280</span> Add docstring for default
<span class="hash">163a9c3</span> <span class="branch">(slovak)</span> Add docstring for slovak
<span class="hash">bd67d8d</span> Fix slovak
<span class="hash">75fcf88</span> Add slovak
<span class="hash">a31caf9</span> <span class="branch">(french)</span> Add docstring for french
<span class="hash">6d348f3</span> Add french
<span class="hash">4b4a8ad</span> Add hello.py
<span class="hash">60d4d94</span> Initial commit
</pre>
:::
::: {.column width="50%"}
Rebase (7):

<pre class="tree">
<span class="hash">ab2fda1</span> <span class="branch">(main, slovak)</span> Add docstring for slovak
<span class="hash">806b97a</span> Add slovak
<span class="hash">5f6f019</span> <span class="branch">(french)</span> Add docstring for french
<span class="hash">ea40a3b</span> Add french
<span class="hash">0297280</span> Add docstring for default
<span class="hash">4b4a8ad</span> Add hello.py
<span class="hash">60d4d94</span> Initial commit
</pre>

:::
:::


## Exercises (2) {.exercise #exercise-2-merge-rebase}

::: {.exercise}

1. Clone two copies of the [test repository](https://github.com/bbrrck/zoo.git):
```bash
git clone https://github.com/bbrrck/zoo.git zoo-merge
git clone https://github.com/bbrrck/zoo.git zoo-rebase
```
2. In the `zoo-merge` repository:
    a. Merge the `origin/krokodil` and `origin/gorila` branches into the local `main` branch using the `git merge` command.
    b. Resolve any conflicts that arise in both cases.

*(continued on the next slide)*
:::

## Exercises (2) {.exercise #exercise-2-merge-rebase-2}

::: {.exercise font-size="80%"}

3. In the `zoo-rebase` repository:
    a. Switch to the `gorila` branch and rebase it onto the `main` branch using `git rebase`. Resolve any conflicts that arise.
    b. Switch to the `main` branch and `git merge` the `gorila` branch into it.
    c. Switch to the `krokodil` branch and rebase if onto the `main` branch using `git rebase -i`. Mark the middle commit as `fixup`. Resolve conflicts.
    d. Switch to the `main` branch and `git merge` the `krokodil` branch into it.
4. Use the `git log` command to compare the state of both repositories.
5. What would change in the result if you skipped step 3b?

:::

## Sidebar: Squash Merge

`git merge --squash` creates a single commit on the target branch.

Usage:

```bash
# 1. checkout to the branch you want to merge into
git checkout main

# 2. perform the squash merge
git merge --squash slovak

# 3. commit the changes
git commit -m "Squash slovak"
```

## Sidebar: Squash Merge

::: {.columns}
::: {.column width="50%"}
Merge:
<pre class="tree">
*   <span class="hash">cef4a72</span> <span class="branch">(main)</span> Merge branch 'slovak'
|\
| * <span class="hash">163a9c3</span> <span class="branch">(slovak)</span> Add docstring for slovak
| * <span class="hash">bd67d8d</span> Fix slovak
| * <span class="hash">75fcf88</span> Add slovak
* |   <span class="hash">bc3f86b</span> Merge branch 'french'
|\ \
| * | <span class="hash">a31caf9</span> <span class="branch">(french)</span> Add docstring for french
| * | <span class="hash">6d348f3</span> Add french
| |/
* / <span class="hash">0297280</span> Add docstring for default
|/
* <span class="hash">4b4a8ad</span> Add hello.py
* <span class="hash">60d4d94</span> Initial commit
</pre>:::
::: {.column width="50%"}
Squash Merge:
<pre class="tree">
* <span class="hash">f3492de</span> <span class="branch">(main)</span> Squash french
* <span class="hash">d23ef42</span> Squash slovak
* <span class="hash">54b75b3</span> Add docstring for default
| * <span class="hash">437cd19</span> <span class="branch">(slovak)</span> Add docstring for slovak
| * <span class="hash">5a92065</span> Fix slovak
| * <span class="hash">c1344d5</span> Add slovak
|/
| * <span class="hash">0962e07</span> <span class="branch">(french)</span> Add docstring for french
| * <span class="hash">7571e67</span> Add french
|/
* <span class="hash">de2c4ac</span> Add hello.py
* <span class="hash">944ce4e</span> Initial commit
</pre>
:::
:::

## Sidebar: Squash Merge

::: {.columns}
::: {.column width="50%"}
Merge (10):
<pre class="tree">
<span class="hash">cef4a72</span> <span class="branch">(main)</span> Merge branch 'slovak'
<span class="hash">bc3f86b</span> Merge branch 'french'
<span class="hash">0297280</span> Add docstring for default
<span class="hash">163a9c3</span> <span class="branch">(slovak)</span> Add docstring for slovak
<span class="hash">bd67d8d</span> Fix slovak
<span class="hash">75fcf88</span> Add slovak
<span class="hash">a31caf9</span> <span class="branch">(french)</span> Add docstring for french
<span class="hash">6d348f3</span> Add french
<span class="hash">4b4a8ad</span> Add hello.py
<span class="hash">60d4d94</span> Initial commit
</pre>
:::
::: {.column width="50%"}
Squash Merge (5):
<pre class="tree">
<span class="hash">f3492de</span> <span class="branch">(main)</span> Squash french
<span class="hash">d23ef42</span> Squash slovak
<span class="hash">54b75b3</span> Add docstring for default
<span class="hash">de2c4ac</span> Add hello.py
<span class="hash">944ce4e</span> Initial commit
</pre>
:::
:::

::: {.warning}
After performing a squash merge, you should always delete the feature branch. 
::: 
